apiVersion: v2
name: inbox-zero
description: A Helm chart for running Zynbox on Kubernetes
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - inbox-zero
  - email
  - ai
  - nextjs
home: https://zynbox.cloud
sources:
  - https://github.com/elie222/inbox-zero
maintainers:
  - name: Zynbox
